BOARD_TAG = arduino_due_x
ARCHITECTURE = sam
ARDUINO_LIBS = DueTimer AnalogLibV1
#CXXFLAGS=-DEMULATE_HARDWARE -DHARDWARE_SEED=12345
#CPPFLAGS=${CXXFLAGS}
ARDUINO_LIB_PATH=${PWD}/lib
#USER_LIB_PATH=/home/jack/Arduino/libraries

include /usr/local/opt/arduino-mk/Sam.mk
